#!/bin/bash

# Print full path of passed files
path()
{
  (for file in $@; do \
    readlink -f "$file"; \
  done) | tr '\n' ' '
  echo
}

# Print arguments
args()
{
  for arg in "$@"; do
    echo "$arg"
  done
}

# Vim Notes plugin
note()
{
  if [ $# -lt 1 ]; then
    gvim +Note
  else
    i=0
    arg=()
    for n in "$@"; do
      arg[$i]="+Note ${n}"
      : $((i++))
    done
    gvim "${arg[@]}"
  fi
}

# Wikipedia lookup
wiki()
{
  dig +short txt "$*".wp.dg.cx | perl -pe's/\\(\d{1,3})/chr $1/eg' | fmt
}

# Silly coffee pot
coffee()
{
  while true; do
    clear
    echo -e "   )\n  (\nC[_]"
    sleep .1
    clear
    echo -e "  | \n  |\nC[_]"
    sleep .1
    clear
    echo -e " (  \n  )\nC[_]"
    sleep .1
    clear
    echo -e "  |\n  |\nC[_]"
    sleep .1
  done
}

# Thesaurus
[ -f "${BASH_HOME}/func_thesaurus" ] && source "${BASH_HOME}/func_thesaurus"
